AWSTemplateFormatVersion: 2010-09-09
Description: Billing Alarm to Monitor Your Estimated AWS Charges


Parameters:

  Email:
    Type: String
    Description: Email address on which alarm email will be sent
  Threshold:
    Type: Number
    Description: The amount of money over which the alarm will be sent


Resources:

  BillingAlarmSNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: billing_alarm_topic
      Subscription:
      - Endpoint: !Ref Email
        Protocol: email

  BillingAlarm:
    Type: AWS::CloudWatch::Alarm
    DependsOn: BillingAlarmSNSTopic
    Properties:
      AlarmName: AWS Billing Alarm
      AlarmDescription: Billing Alarm to Monitor My Estimated AWS Charges
      AlarmActions:
        - !Ref BillingAlarmSNSTopic
      Period: 86400               # 1 day - time in seconds (multiples of 60)
      ComparisonOperator: GreaterThanOrEqualToThreshold
      EvaluationPeriods: 1
      Threshold: !Ref Threshold
      Dimensions:
        - Name: currency
          Value: USD
      TreatMissingData: ignore
      Statistic: Maximum
      MetricName: EstimatedAWSCharges
      Namespace: AWS/Billing
      



