AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: App deployed on fargate.


Resources:

  VpcStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./vpc.yml

  LoadBalancerStack:
    DependsOn: VpcStack
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./loadbalancer.yml
      Parameters:
        Vpc: !GetAtt VpcStack.Outputs.Vpc
        PubSubnet1: !GetAtt VpcStack.Outputs.PubSubnet1
        PubSubnet2: !GetAtt VpcStack.Outputs.PubSubnet2

  EcsStack:
    DependsOn: LoadBalancerStack
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./ecs.yml
      Parameters:
        Vpc: !GetAtt VpcStack.Outputs.Vpc
        LoadBalancerSecurityGroup: !GetAtt LoadBalancerStack.Outputs.LoadBalancerSecurityGroup

  FargateStack:
    DependsOn: EcsStack
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./fargate.yml
      Parameters:
        Vpc: !GetAtt VpcStack.Outputs.Vpc
        PubSubnet1: !GetAtt VpcStack.Outputs.PubSubnet1
        PubSubnet2: !GetAtt VpcStack.Outputs.PubSubnet2
        PrivSubnet1: !GetAtt VpcStack.Outputs.PrivSubnet1
        PrivSubnet2: !GetAtt VpcStack.Outputs.PrivSubnet2
        LoadBalancer: !GetAtt LoadBalancerStack.Outputs.LoadBalancer
        LoadBalancerSecurityGroup: !GetAtt LoadBalancerStack.Outputs.LoadBalancerSecurityGroup
        FargateContainerSecurityGroup: !GetAtt EcsStack.Outputs.FargateContainerSecurityGroup
        EcsTaskExecutionRole: !GetAtt EcsStack.Outputs.EcsTaskExecutionRole
        ECSCluster: !GetAtt EcsStack.Outputs.ECSCluster

