AWSTemplateFormatVersion: 2010-09-09
Description: DynamoDB table to test migration script


Parameters:

  TableName:
    Type: String
    Description: Table name


Resources:

  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
      - AttributeName: id
        AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema: 
      - AttributeName: id
        KeyType: HASH
      PointInTimeRecoverySpecification: 
        PointInTimeRecoveryEnabled: False
      TableName: !Ref TableName
      Tags : 
      - Key: project
        Value: edu